### ISSUE TITLE
Can't record video in Station mode

### ISSUE THREAD

**Issue by bknill** [luckylz2git/Ponerine#1]
Hi Luckylz, 

Great app. I'm having major difficulty recording video through the app, it doesn't seem to be sending the commands properly. The camera flashes but no video is saved to the SD card, and 'stop recording' never becomes available.

**Comment by luckylz2git** [comment]
which app you're testing? ponerine.m or ponerine.s?

**Comment by bknill** [comment]
Hi With both. Ponerine.m will start all cameras recording, but nothing is actually stored on cards - ponerine.s seems to start recording and the camera then crashes - nothing is on card. 

Same thing happens with the CC windows app.

The app works fine when camera in AP mode, records video perfectly. It's just failing in Station Mode. I've tried using the scripts generated by the app and scripts from the store.

**Comment by bknill** [comment]
Same thing happens with the CC windows app

**Comment by luckylz2git** [comment]
try: 
1. update firmware to 1.2.13;
2. try to format the micro sd card in camera.

**Comment by bknill** [comment]
OK I have tried both of those. Will try again.

**Comment by bknill** [comment]
Thanks yep tried both of those. Same thing. Camera seems to start recording, and then after a few moments restarts itself. This doesn't happen in AP mode, just station mode. Weird!

**Comment by luckylz2git** [comment]
I suggest you should restore cameras to factory setting, and try to put the wifi.sh in /tmp/fuse_a/, not in /tmp/fuse_d/

**Comment by bknill** [comment]
OK thanks will try. 

How do I access those folders? Via the CC app?

**Comment by bknill** [comment]
Maybe this is it

![image](https://cloud.githubusercontent.com/assets/7074483/11465393/3f9571f2-979d-11e5-81b3-498b717ae10f.png)

I installed the Station script via your app and there is no wifi.sh in fuse_a or fuse_d

Fuse_d
![image](https://cloud.githubusercontent.com/assets/7074483/11465406/50df9b9a-979d-11e5-9035-7959e2d90aca.png)

fuse_a
![image](https://cloud.githubusercontent.com/assets/7074483/11465474/bd608ea0-979d-11e5-8778-2b322e70dd7a.png)

**Comment by luckylz2git** [comment]
try to figure out at: https : / / dashcamtalk . com / forum / forums / xiaomi . 153 /

**Comment by bknill** [comment]
Thanks Luckylz, I've been through that forum 100 times, I can find a few people that have had the same issue as me but no one seems to have solved it. I've put some posts up and not had any responses yet. You've been really helpful thanks, anywhere I can make a donation if I can get it working?

**Comment by luckylz2git** [comment]
show me your post, or leave me a message there.

**Comment by bknill** [comment]
I found wifi.sh it's already in fuse_a

![image](https://cloud.githubusercontent.com/assets/7074483/11465570/d255400c-979e-11e5-8f6b-62889be34b0f.png)

Anything else you can think might be causing it?

**Comment by bknill** [comment]
https://dashcamtalk.com/forum/threads/record-video-in-station-mode-crashes-camera.15444/
