### ISSUE TITLE
VLC for Android not working

### ISSUE THREAD

**Issue by JohnRSim** [luckylz2git/Ponerine#2]
Running PonerineS 0.1.4 

Steps:
Connect camera.
Select "Preview On" button it flashes blue once 
Select home button.
Open VLC for Android 
Enter rtsp://cameraIP:554/live
and I get error with playback stream.

I can access RTSP stream on windows8 in VLC but not on mobile?
Do you have any ideas?

Thanks
J.

**Comment by luckylz2git** [comment]
if you use the same android phone, you can not exit the app if you want to use VLC.
you should switch to VLC by click "Home" button and open VLC.

**Comment by JohnRSim** [comment]
I do not exit the app but get error with playback messages in VLC for android on my Samsung S6 and One Plus one phone. 

Running Android 5.1.1 all other functions appear to work fine.

**Comment by luckylz2git** [comment]
if you got rtsp on win8, then I think you should try another VLC version for your mobile phone.

**Comment by JohnRSim** [comment]
What android do you have and which OS?
I have read some androids devices don't support RTSP streams whilst the android OS does.

I've tried Android video, rtsp player and vlc for android with no success but windows works fine.

Thanks

**Comment by luckylz2git** [comment]
Android 4.4.2 works good with "VLC for Android"

**Comment by JohnRSim** [comment]
ok I'll see if I can find a 4.x device.
I presume the xiaomi yi is using RTSP to stream its preview when on wifi direct?

maybe its something on my network blocking going through router? 
But then why does it work for windows?

**Comment by JohnRSim** [comment]
Have you been able to get the mjpeg to work?
